blog_app/urls.py
# from django.conf.urls import url
from django.urls import path
from blog_app import views

app_name = "blog_app"

urlpatterns = [
    path('', views.blog, name='blog'),
    path('<str:slug>', views.blog_details, name='blog_details'),

]

tour_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('book/', include('book_app.urls')),
    path('package/', include('package_app.urls')),
    path('services/', include('services_app.urls')),
    path('gallery/', include('gallery_app.urls')),
    path('contact/', include('contact_app.urls')),
    path('blog/', include('blog_app.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog_app/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Blog(models.Model):
    blog_title = models.CharField(max_length=255, verbose_name='Put a Title')
    short_description = models.TextField(max_length=500)
    blog_content = RichTextField()
    blog_image = models.ImageField(upload_to='blog_images', verbose_name='Image', blank=False, null=False)
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        ordering = ['-publish_date',]

    def __str__(self):
        return str(self.blog_title)

blog_app/views.py
from django.shortcuts import render
from blog_app.models import Blog
# Create your views here.


def blog(request):
    # all_blog = Blog.objects.order_by('blog_title')
    all_blog = Blog.objects.all().order_by('-id')

    print("####################")
    print(all_blog)
    print("####################")

    diction = {'all_blog': all_blog}
    return render(request,'blog_app/blog.html', context = diction)



def blog_details(request, slug):

    # access package without loop in template
    blog = Blog.objects.get(slug=slug)

    diction = {'blog':blog}
    return render(request, 'blog_app/blog_details.html', context = diction)

templates/blog_app/blog.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">


{% extends 'base.html' %}
{% block title %}BGD Tour & Travel | Blog{% endblock %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block body %}


<style>
    .btn{
  display: inline-block;
  margin-top: 1rem;
  background:var(--orange);
  color:#fff;
  padding:.8rem 3rem;
  border:.2rem solid var(--orange);
  cursor: pointer;
  font-size: 1.7rem;
}

.btn:hover{
  background:rgba(255, 165, 0,.2);
  color:var(--orange);
}
</style>


<section id="blogpage">
    <div class="container" style="margin-top: 150px; margin-bottom: 50px;">
        {% for row in all_blog %}
        <a href="{% url 'blog_app:blog_details' slug=row.slug %}" style="color: black;"><h1 class="mt-5 mb-3 font-weight-bold">{{ row.blog_title }}</h1></a>
        <i>
            <h4>Publish On: {{ row.publish_date }}</h4>
        </i>
        <br>
        <div class="row">
            <div class="col-sm-4">
                <img src="{{ row.blog_image.url }}" width="100%">
            </div>
            <div class="col-sm-8">
                <h3><p class="text-justify">{{ row.short_description | linebreaks }}</p></h3>
            </div>
        </div>

        <hr>

        {% endfor %}

    </div>
</section>

{% endblock %}

templates/blog_app/blog_details.html
{% extends 'base.html' %}
{% block title %}BGD Tour & Travel | Blog Details{% endblock %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block body %}



<style>
    .btn{
  display: inline-block;
  margin-top: 1rem;
  background:var(--orange);
  color:#fff;
  padding:.8rem 3rem;
  border:.2rem solid var(--orange);
  cursor: pointer;
  font-size: 1.7rem;
}

.btn:hover{
  background:rgba(255, 165, 0,.2);
  color:var(--orange);
}
</style>



<div class="container" style="margin-left: 10%; margin-right: 10%; margin-top: 100px; margin-bottom: 5%;">

    <div class="row">
        <div class="clo-sm-6 content" style="font-size: 50px; text-align: center;">
            <h3>"{{ blog.blog_title }}"</h3>
        </div>

        <br>
        <br>

        <div class="clo-sm-6">
            <img src="{{ blog.blog_image.url }}" width="40%" style="margin-left:25%">
        </div>

        <br>
        <br>

        <h2>
            {{ blog.blog_content | safe }}
        </h2>
    </div>

</div>

{% endblock %}