blog_app/urls.py
# from django.conf.urls import url
from django.urls import path
from blog_app import views

app_name = "blog_app"

urlpatterns = [
    path('', views.blog, name='blog'),
    path('<str:slug>', views.blog_details, name='blog_details'),

]

services_app/urls.py
# from django.conf.urls import url
from django.urls import path
from services_app import views

app_name = "services_app"

urlpatterns = [
    path('', views.services, name='services'),
    path('visa/', views.visa, name='visa'),
    path('<str:slug>', views.destination_details, name='destination_details'),
    path('country/<str:slug>', views.country_details, name='country_details'),
    path('flight/', views.flight, name='flight'),
    path('passport/', views.passport, name='passport'),
]

tour_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('book/', include('book_app.urls')),
    path('package/', include('package_app.urls')),
    path('services/', include('services_app.urls')),
    path('gallery/', include('gallery_app.urls')),
    path('contact/', include('contact_app.urls')),
    path('blog/', include('blog_app.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

services_app/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Country(models.Model):
    name = models.CharField(max_length=50)
    description = RichTextField(blank=True, null=True)
    flag_image = models.ImageField(upload_to='flag_images')
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        ordering = ['name',]

    def __str__(self):
        return str(self.name)
    


class Visa(models.Model):
    where_from = models.ForeignKey(Country, on_delete=models.CASCADE, related_name='where_from', verbose_name="Where am I From?")
    where_going = models.ForeignKey(Country, on_delete=models.CASCADE, related_name='where_going', verbose_name="Where am I Going?")
    type_name = (
        (1, "Business"),
        (2, "Tourist"),
        (3, "Medical"),
        (3, "Student"),
    )
    visa_type = models.IntegerField(choices=type_name)
    which_country_passport = models.ForeignKey(Country, on_delete=models.CASCADE, related_name='which_country_passport')
    name = models.CharField(max_length=250)
    email = models.EmailField()
    mobile = models.CharField(max_length=15)
    passport_number = models.CharField(max_length=100)
    nid_number = models.CharField(max_length=100, blank=True, null=True, verbose_name="NID Number")
    occupation_name = (
        (1, "Student"),
        (2, "Government Job"),
        (3, "Private Job"),
        (4, "Business"),
        (5, "Teacher"),
        (6, "Doctor"),
        (7, "Other"),
    )
    occupation = models.IntegerField(choices=occupation_name)
    gender_name = (
        (1, "Male"),
        (2, "Female"),
    )
    gender = models.IntegerField(choices=gender_name)
    date_of_birth = models.DateField()

    def __str__(self):
        return str(self.name)
    


class Popular_Destination(models.Model):
    name = models.CharField(max_length=50)
    description = RichTextField(blank=True, null=True)
    feature_image = models.ImageField(upload_to='flag_images')
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        ordering = ['name',]

    def __str__(self):
        return str(self.name)





class Flight(models.Model):
    flight_type = models.CharField(max_length=250)
    flying_from = models.CharField(max_length=250)
    flying_to = models.CharField(max_length=250)
    departing = models.CharField(max_length=250)
    returning = models.CharField(max_length=250)
    adults = models.CharField(max_length=250)
    children = models.CharField(max_length=250)
    travel_class =models.CharField(max_length=250)


    def __str__(self):
        return str(self.flight_type)
    


class Passport(models.Model):
    full_name = models.CharField(max_length=50)
    gender_name = (
        (1, "Male"),
        (2, "Female"),
    )
    gender = models.IntegerField(choices=gender_name)
    date_of_birth = models.DateField()
    birth_certificate = models.CharField(max_length=50)
    nid_number = models.CharField(max_length=100, blank=True, null=True, verbose_name="NID Number")
    occupation_name = (
        (1, "Student"),
        (2, "Government Job"),
        (3, "Private Job"),
        (4, "Business"),
        (5, "Teacher"),
        (6, "Doctor"),
        (7, "Other"),
    )
    occupation = models.IntegerField(choices=occupation_name)
    father_name = models.CharField(max_length=50)
    father_nid = models.CharField(max_length=50)
    mother_name = models.CharField(max_length=50)
    mother_nid = models.CharField(max_length=50)
    present_address = models.TextField()
    permanent_address = models.TextField()
    email = models.EmailField()
    mobile = models.CharField(max_length=15)

    def __str__(self):
        return str(self.full_name)
    

services_app/forms.py
from django import forms
from django.forms.widgets import NumberInput, TextInput, EmailInput
from services_app.models import Visa, Passport


class VisaForm(forms.ModelForm):
    # email = forms.CharField(widget = forms.TextInput(attrs={'placeholder': 'Enter Your Email'}), label="")
    # name = forms.CharField(widget = forms.TextInput(attrs={'placeholder': 'Enter Your Number'}), label="")
    date_of_birth = forms.DateField(widget = NumberInput(attrs={'type': 'date'}))
    

    class Meta:
        model = Visa
        fields = ['where_from', 'where_going', 'visa_type', 'which_country_passport', 'name', 'email', 'mobile', 'passport_number', 'nid_number', 'occupation', 'gender', 'date_of_birth']
        # fields = '__all__'




class PassportForm(forms.ModelForm):
    date_of_birth = forms.DateField(widget = NumberInput(attrs={'type': 'date'}))

    class Meta:
        model = Passport
        fields = '__all__'

        # widgets = {
        #     'full_name': TextInput(attrs={
        #         'class': "form-control",
        #         'style': 'max-width: 700px; height: 100px;',
        #         'placeholder': 'Name'
        #         }),
        #     'email': EmailInput(attrs={
        #         'class': "form-control", 
        #         'style': 'max-width: 300px;',
        #         'placeholder': 'Email'
        #         })
        # }

services_app/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect

from django.urls import reverse, reverse_lazy
from services_app.forms import VisaForm, PassportForm
from services_app.models import Country, Flight, Popular_Destination

from django.contrib import messages

# Create your views here.

def services(request):

    return render(request,'services_app/services.html')


def visa(request):
    form = VisaForm()
    registered = False
    all_country = Country.objects.all().order_by('-id')
    popular_destination = Popular_Destination.objects.all().order_by('-id')
    if request.method == "POST":
        form = VisaForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
            form = VisaForm()
            # return HttpResponseRedirect(reverse('services_app:services'))
    diction = {'form':form, 'all_country':all_country, 'registered':registered, 'popular_destination':popular_destination}
    return render(request,'services_app/visa.html', context = diction)


def destination_details(request, slug):

    # access country without loop in template
    destination = Popular_Destination.objects.get(slug=slug)

    diction = {'destination':destination}

    return render(request, 'services_app/popular_desti_details.html', context = diction)


def country_details(request, slug):

    # access country without loop in template
    country = Country.objects.get(slug=slug)

    diction = {'country':country}

    return render(request, 'services_app/country_details.html', context = diction)


def flight(request):
    if request.method == 'POST':
        flight_type = request.POST.get('flight_type')
        flying_from = request.POST.get('flying_from')
        flying_to = request.POST.get('flying_to')
        departing = request.POST.get('departing')
        returning = request.POST.get('returning')
        adults = request.POST.get('adults')
        children = request.POST.get('children')
        travel_class = request.POST.get('travel_class')

        form = Flight(
            flight_type = flight_type,
            flying_from = flying_from,
            flying_to = flying_to,
            departing = departing,
            returning = returning,
            adults = adults,
            children = children,
            travel_class = travel_class
        )

        form.save()

        messages.success(request, "Flight Booking Successfully.")
        return redirect('services_app:flight')

    return render(request,'services_app/flight.html')


def passport(request):
    form = PassportForm()
    registered = False
    if request.method == "POST":
        form = PassportForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
            form = PassportForm()
            # return HttpResponseRedirect(reverse('services_app:passport'))
    diction = {'form':form, 'registered': registered}
    return render(request,'services_app/passport.html', context = diction)

templates/services_app/country_details.html
{% extends 'base.html' %}
{% block title %}BGD Tour & Travel | Country Details{% endblock %}
{% load static %}
{% block body %}



<style>
    .btn{
  display: inline-block;
  margin-top: 1rem;
  background:var(--orange);
  color:#fff;
  padding:.8rem 3rem;
  border:.2rem solid var(--orange);
  cursor: pointer;
  font-size: 1.7rem;
}

.btn:hover{
  background:rgba(255, 165, 0,.2);
  color:var(--orange);
}
</style>



<div class="container" style="margin-left: 10%; margin-right: 10%; margin-top: 100px; margin-bottom: 5%;">

    <div class="content">
        <h3>"{{ country.name }}" - Open for Tourism, here's what you'll need</h3>
    </div>

    <br>

    <div style="margin-top: 50px;">
        <p>{{ country.description | safe }}</p>
    </div>


</div>


{% endblock %}

templates/services_app/popular_desti_details.html
{% extends 'base.html' %}
{% block title %}BGD Tour & Travel | Destination Details{% endblock %}
{% load static %}
{% block body %}



<style>
    .btn{
  display: inline-block;
  margin-top: 1rem;
  background:var(--orange);
  color:#fff;
  padding:.8rem 3rem;
  border:.2rem solid var(--orange);
  cursor: pointer;
  font-size: 1.7rem;
}

.btn:hover{
  background:rgba(255, 165, 0,.2);
  color:var(--orange);
}
</style>



<div class="container" style="margin-left: 10%; margin-right: 10%; margin-top: 100px; margin-bottom: 5%;">

    <div class="content">
        <h3>"{{ destination.name }}" - Open for Tourism, here's what you'll need</h3>
    </div>

    <br>

    <div style="margin-top: 50px;">
        <p>{{ destination.description | safe }}</p>
    </div>


</div>


{% endblock %}

templates/services_app/services.html
{% extends 'base.html' %}
{% block title %}BGD Tour & Travel | Services{% endblock %}
{% load static %}
{% block body %}



<style>
    .btn{
  display: inline-block;
  margin-top: 1rem;
  background:var(--orange);
  color:#fff;
  padding:.8rem 3rem;
  border:.2rem solid var(--orange);
  cursor: pointer;
  font-size: 1.7rem;
}

.btn:hover{
  background:rgba(255, 165, 0,.2);
  color:var(--orange);
}
</style>




<!-- services section starts  -->

<section class="services" id="services">

    <h1 class="heading">
        <span>s</span>
        <span>e</span>
        <span>r</span>
        <span>v</span>
        <span>i</span>
        <span>c</span>
        <span>e</span>
        <span>s</span>
    </h1>

    <div class="box-container">

        
         
        <div class="box">
            <a href="{% url 'services_app:flight' %}"><i class="fas fa-plane"></i></a>
            <a href="{% url 'services_app:flight' %}">
                <h3>Air Ticket</h3>
            </a>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore commodi earum, quis voluptate exercitationem ut minima itaque iusto ipsum corrupti!</p>
        </div>
        
        
        <div class="box">
            <i class="fas fa-bus"></i>
            <a href="#"><h3>Bus Ticket</h3></a>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore commodi earum, quis voluptate exercitationem ut minima itaque iusto ipsum corrupti!</p>
        </div>


        <div class="box">
            <a href="{% url 'services_app:passport' %}" target="_blank"><i class="fas fa-passport"></i></a>
            <a href="{% url 'services_app:passport' %}" target="_blank"><h3>Passport Services</h3></a>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore commodi earum, quis voluptate exercitationem ut minima itaque iusto ipsum corrupti!</p>
        </div>


        <div class="box">
            <a href="{% url 'services_app:visa' %}" target="_blank"><i class="fab fa-cc-visa"></i></a>
            <a href="{% url 'services_app:visa' %}" target="_blank"><h3>Visa Processing</h3></a>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore commodi earum, quis voluptate exercitationem ut minima itaque iusto ipsum corrupti!</p>
        </div>


        <div class="box">
            <i class="fas fa-hotel"></i>
            <a href="#"><h3>Hotel Booking</h3></a>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore commodi earum, quis voluptate exercitationem ut minima itaque iusto ipsum corrupti!</p>
        </div>


        <div class="box">
            <i class="fas fa-hand-holding-usd"></i>
            <a href="#"><h3>Money Transfer</h3></a>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore commodi earum, quis voluptate exercitationem ut minima itaque iusto ipsum corrupti!</p>
        </div>


        
        <div class="box">
            <i class="fas fa-bullhorn"></i>
            <a href="#"><h3>safty guide</h3></a>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore commodi earum, quis voluptate exercitationem ut minima itaque iusto ipsum corrupti!</p>
        </div>


    </div>

</section>

<!-- services section ends -->

{% endblock %}

templates/services_app/visa.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />



<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>




<style>
  .card {
    border-radius: 0.7rem;
  }


  #myDIV {
    width: 100%;
    /* padding: 50px; */
    text-align: center;
    background-color: rgb(238, 238, 238);
    /* margin-top: 10px; */
    display: none;
    padding-bottom: 15px;
  }


  i.fa {
    font-size: 50px;
    cursor: pointer;
    user-select: none;
  }

  .fa:hover {
    color: darkblue;
  }


  .btn{
    display: inline-block;
    margin-top: 1rem;
    background:var(--orange);
    color:#fff;
    padding:.8rem 3rem;
    border:.2rem solid var(--orange);
    cursor: pointer;
    font-size: 1.7rem;
  }
  
  .btn:hover{
    background:rgba(255, 165, 0,.2);
    color:var(--orange);
  }


</style>

{% extends 'base.html' %}
{% block title %}BGD Tour & Travel | Visa{% endblock %}
{% load static %}
{% block body %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}


<!-- Title Information Part Start -->

<section class="container" style="margin-top: 100px;">
  <h1 class="text-center fw-bolder">
    Online Travel Visa Check. Find Visa information for all countries.
  </h1>

  <h3 class="text-center fw-bolder">Simplifying Travel Around The World.</h3>
  <br>

</section>

<!-- Title Information Part End -->


{% if registered == True %}

<div class="alert alert-warning alert-dismissible fade show" style="margin-left: 25%; margin-right: 25%;"
    role="alert">
    <strong>Successfully Applied For Visa!</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

{% endif %}


<!-- Visa Image Part Start -->

<section class="img-fluid">
  <img src="/static/images/visa/visa.jpg" width="100%" alt="image">
</section>

<!-- Visa Image Part End -->



<!-- Visa Process Form Section Start -->

<section>

  <div class="row">
    <div class="col-12 pt-2">


      <div>
        <h1 class="text-center mb-5" style="font-weight: bold;">SUBMIT YOUR INFORMATION FOR VISA</h1>
        <form method="POST">
          {% csrf_token %}


          <div class="row fw-bold">
            <div class="col-12 col-lg-6">
              {{ form.where_from|as_crispy_field }}
            </div>
            <div class="col-12 col-lg-6">
              {{ form.where_going|as_crispy_field }}
            </div>
          </div>



          <!-- Most Popular Destinations Part Start -->

          <div style="margin-top: 50px;">
            <h1 class="text-center mb-5" style="font-weight: bold;">Most Popular Destinations</h1>
          </div>

          <div class="row" style="margin-top: 50px; margin-bottom: 50px;">

            {% for destination in popular_destination %}
            <div class="col-12 col-lg-3">
              <div class="card">
                <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                  <a href="{% url 'services_app:destination_details' slug=destination.slug %}"><img src="{{ destination.feature_image.url }}" class="img-fluid"/></a>
                  <a href="#!">
                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                  </a>
                </div>
                <div class="card-body">
                  <a href="{% url 'services_app:destination_details' slug=destination.slug %}" style="text-decoration: none;"><h1 class="card-title" style="text-align: center; font-weight: bold;">{{ destination.name }}</h1></a>
                  <!-- <a href="#!" class="btn btn-primary">Learn More</a> -->
                </div>
              </div>
            </div>
            {% endfor %}

          </div>

          <!-- Most Popular Destinations Part End -->



          <!-- View All Country Part Start -->

          <div class="text-center" style="margin-bottom: 50px;">
            <button onclick="myFunction()" type="button" class="btn btn-primary">View All Country</button>
          </div>

          <div id="myDIV" class="row text-center">

            <div class="row row-cols-1 row-cols-md-6 g-4">

              {% for country in all_country %}

              <div class="col">
                <div class="card">
                  <a href="{% url 'services_app:country_details' slug=country.slug %}"><img src="{{ country.flag_image.url }}" class="card-img-top" alt="..."></a>
                  <div class="card-body">
                    <a href="{% url 'services_app:country_details' slug=country.slug %}" style="text-decoration: none;"><h1 class="card-title">{{ country.name }}</h1></a>
                  </div>
                </div>
              </div>

              {% endfor %}

            </div>

          </div>

          <!-- View All Country Part End -->



          <br>
          <br>
          <br>



          <div class="row">
            <div class="col-12 col-lg-6">
              {{ form.visa_type|as_crispy_field }}
            </div>
            <div class="col-12 col-lg-6">
              {{ form.which_country_passport|as_crispy_field }}
            </div>
          </div>


          <div class="row">
            <div class="col-12 col-lg-6">
              {{ form.name|as_crispy_field }}
            </div>
            <div class="col-12 col-lg-6">
              {{ form.email|as_crispy_field }}
            </div>
          </div>


          <div class="row">
            <div class="col-12 col-lg-6">
              {{ form.nid_number|as_crispy_field }}
            </div>
            <div class="col-12 col-lg-6">
              {{ form.passport_number|as_crispy_field }}
            </div>
          </div>


          <div class="row">
            <div class="col-12 col-lg-6">
              {{ form.mobile|as_crispy_field }}
            </div>
            <div class="col-12 col-lg-6">
              {{ form.occupation|as_crispy_field }}
            </div>
          </div>


          <div class="row">
            <div class="col-12 col-lg-6">
              {{ form.gender|as_crispy_field }}
            </div>
            <div class="col-12 col-lg-6">
              {{ form.date_of_birth|as_crispy_field }}
            </div>
          </div>


          <div class="text-center mt-5">
            <button type="submit" class="btn btn-outline-primary btn-lg">Applay Now</button>
          </div>
        </form>
      </div>
    </div>
  </div>

</section>

<!-- Visa Process Form Section End -->



<!-- Why Choose Us Part Start -->

<section>
  <h1>Why Choose Us:</h1>
  <div class="row">
    <div class="col-sm-3">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title">Speed and Simplicity</h2>
          <h4 class="card-text">
            Easy, traveler-friendly application process. Simple and much less
            complicated than dealing with foreign governments.
          </h4>
        </div>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title">Get Approved</h2>
          <h4 class="card-text">
            All documents are reviewed by a team of immigration experts. Our
            staff is well-trained and offers years of experience All documents
            are reviewed.
          </h4>
        </div>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title">Secure and Safe</h2>
          <h4 class="card-text">
            World-class data centers and state-of-the-art security. Your credit
            card information will never be exposed to any government websites!
          </h4>
        </div>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title">Awesome support</h2>
          <h4 class="card-text">
            Our customer support is ready to help 24/7. We want you to enjoy
            your travels and avoid the stress of getting a visa! Our customer
            support
          </h4>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Why Choose Us Part End -->



<!-- Testimonial Part Start -->

<section style="color: #000; background-color: #f3f2f2">
  <div class="container py-5">
    <div class="row d-flex justify-content-center">
      <div class="col-md-10 col-xl-8 text-center">
        <h1 class="fw-bold mb-4">Testimonials</h1>
        <h4 class="mb-4 pb-2 mb-md-5 pb-md-0">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit, error
          amet numquam iure provident voluptate esse quasi, veritatis totam
          voluptas nostrum quisquam eum porro a pariatur.
        </h4>
      </div>
    </div>

    <div class="row text-center">

      <div class="col-md-4 mb-4 mb-md-0">
        <div class="card">
          <div class="card-body py-4 mt-2">
            <div class="d-flex justify-content-center mb-4">
              <img class="rounded-circle" src="/static/images/p111.jpg" width="100" height="100" />
            </div>

            <h5 class="font-weight-bold">Teresa May</h5>

            <!-- <h6 class="font-weight-bold my-3">Founder at ET Company</h6> -->
            <ul class="list-unstyled d-flex justify-content-center">
              <li>
                <i class="fas fa-star fa-sm text-info"></i>
              </li>
              <li>
                <i class="fas fa-star fa-sm text-info"></i>
              </li>
              <li>
                <i class="fas fa-star fa-sm text-info"></i>
              </li>
              <li>
                <i class="fas fa-star fa-sm text-info"></i>
              </li>
              <li>
                <i class="fas fa-star-half-alt fa-sm text-info"></i>
              </li>
            </ul>

            <p class="mb-2">
              <i class="fas fa-quote-left pe-2"></i>Lorem ipsum dolor sit amet,
              consectetur adipisicing elit. Quod eos id officiis hic tenetur
              quae quaerat ad velit ab hic tenetur.
            </p>

          </div>
        </div>
      </div>

      <div class="col-md-4 mb-4 mb-md-0">
        <div class="card">
          <div class="card-body py-4 mt-2">
            <div class="d-flex justify-content-center mb-4">
              <img class="rounded-circle" src="/static/images/p222.png" width="100" height="100" />
            </div>
            <h5 class="font-weight-bold">Maggie McLoan</h5>
            <!-- <h6 class="font-weight-bold my-3">Photographer at Studio LA</h6> -->
            <ul class="list-unstyled d-flex justify-content-center">
              <li>
                <i class="fas fa-star fa-sm text-info"></i>
              </li>
              <li>
                <i class="fas fa-star fa-sm text-info"></i>
              </li>
              <li>
                <i class="fas fa-star fa-sm text-info"></i>
              </li>
              <li>
                <i class="fas fa-star fa-sm text-info"></i>
              </li>
              <li>
                <i class="fas fa-star fa-sm text-info"></i>
              </li>
            </ul>
            <p class="mb-2">
              <i class="fas fa-quote-left pe-2"></i>Autem, totam debitis
              suscipit saepe sapiente magnam officiis quaerat necessitatibus
              odio assumenda perferendis.
            </p>
          </div>
        </div>
      </div>

      <div class="col-md-4 mb-0">
        <div class="card">
          <div class="card-body py-4 mt-2">
            <div class="d-flex justify-content-center mb-4">
              <img class="rounded-circle" src="/static/images/p333.png" width="100" height="100" />
            </div>
            <h5 class="font-weight-bold">Alexa Horwitz</h5>
            <!-- <h6 class="font-weight-bold my-3">Front-end Developer in NY</h6> -->
            <ul class="list-unstyled d-flex justify-content-center">
              <li>
                <i class="fas fa-star fa-sm text-info"></i>
              </li>
              <li>
                <i class="fas fa-star fa-sm text-info"></i>
              </li>
              <li>
                <i class="fas fa-star fa-sm text-info"></i>
              </li>
              <li>
                <i class="fas fa-star fa-sm text-info"></i>
              </li>
              <li>
                <i class="far fa-star fa-sm text-info"></i>
              </li>
            </ul>
            <p class="mb-2">
              <i class="fas fa-quote-left pe-2"></i>Cras sit amet nibh libero,
              in gravida nulla metus scelerisque ante sollicitudin commodo cras
              purus odio, vestibulum in tempus viverra.
            </p>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>

<!-- Testimonial Part End -->

{% endblock %}