blog_app/urls.py
# from django.conf.urls import url
from django.urls import path
from blog_app import views

app_name = "blog_app"

urlpatterns = [
    path('', views.blog, name='blog'),
    path('<str:slug>', views.blog_details, name='blog_details'),

]

home_app/urls.py
# from django.conf.urls import url
from django.urls import path
from home_app import views

app_name = "home_app"

urlpatterns = [
    path('', views.home, name='home'),

]

services_app/urls.py
# from django.conf.urls import url
from django.urls import path
from services_app import views

app_name = "services_app"

urlpatterns = [
    path('', views.services, name='services'),
    path('visa/', views.visa, name='visa'),
    path('<str:slug>', views.destination_details, name='destination_details'),
    path('country/<str:slug>', views.country_details, name='country_details'),
    path('flight/', views.flight, name='flight'),
    path('passport/', views.passport, name='passport'),
]

tour_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('book/', include('book_app.urls')),
    path('package/', include('package_app.urls')),
    path('services/', include('services_app.urls')),
    path('gallery/', include('gallery_app.urls')),
    path('contact/', include('contact_app.urls')),
    path('blog/', include('blog_app.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home_app/models.py
from django.db import models

# Create your models here.


class Home(models.Model):
    video_title = models.CharField(max_length=50)
    video_short_description = models.CharField(max_length=255)
    video_uplode = models.FileField(upload_to='videos_uploaded')

    def __str__(self):
        return str(self.video_title)

home_app/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from home_app.models import Home

# Create your views here.

def home(request):
    # home = Home.objects.all().order_by('-id')
    # home = Home.objects.filter(video_title__in=[0])
    # home = Home.objects.filter()[:1].get()
    
    home = Home.objects.first()
    diction = {'home':home}
    return render(request,'home_app/home.html', context = diction)

templates/home_app/home.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">


{% extends 'base.html' %}
{% block title %}BGD Tour & Travel | Home{% endblock %}
{% load static %}
{% block body %}


<link rel="stylesheet" href="{% static 'css/flight.css' %}">



<!-- home section starts  -->
<section class="home" id="home">

    {% if home %}
    {% comment %} {% for homes in home %} {% endcomment %}
    <div class="content">
        <h3>{{ home.video_title }}</h3>
        <p>{{ home.video_short_description }}</p>
        {% comment %} <a href="#" class="btn">discover more</a> {% endcomment %}
    </div>

    <div class="video-container">
        <video src="{{ home.video_uplode.url }}" id="video-slider" loop autoplay muted></video>
    </div>
    {% comment %} {% endfor %} {% endcomment %}

    {% else %}









    <div class="container rounded shadow-sm" style="margin-top: 200px; margin-bottom: 200px;">
        <form method="post" , action="{% url 'services_app:flight' %}" enctype="multipart/form-data">
            {% csrf_token %}
    
    
    
    
    
            {% if messages %}
            {% for message in messages %}
    
    
             <div class="alert alert-warning alert-dismissible fade show" style="margin-left: 25%; margin-right: 25%; margin-bottom: 100px;" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
    
    
             {% endfor %}
             {% endif %}
    
    
    
    
            
            <div class="row">
    
                <div class="col-md-2 pe-0 col-sm-12">
                    <div class="btn radio-btn mb-3"> <label class="radio"> <input type="radio" value="One Way" name="flight_type"
                                checked>
                            <h1 style="font-weight: bold;">One Way</h1> <span></span>
                        </label> </div>
                </div>
    
                <div class="col-md-2 pe-0 col-sm-12">
                    <div class="btn radio-btn mb-3"> <label class="radio"> <input type="radio" value="Round Trip" name="flight_type">
                            <h1 style="font-weight: bold;">Round Trip</h1> <span></span>
                        </label> </div>
                </div>
    
                <div class="col-md-2 pe-0 col-sm-12">
                    <div class="btn radio-btn mb-3"> <label class="radio"> <input type="radio" value="Multi City" name="flight_type">
                            <h1 style="font-weight: bold;">Multi City</h1> <span></span>
                        </label> </div>
                </div>
    
            </div>
    
            <div class="row">
                <div class="col-md-6 col-12 mb-4">
                    <div class="form-control d-flex flex-column fs-3">
                        <p class="h-blue fw-bold">FLYING FROM</p>
    
                        <select class="border-0 outline-none" name="flying_from" required>
                            <option value="" hidden selected>City or Airport</option>
                            <option value="Dhaka (Hazrat Shahjalal International Airport)">Dhaka (Hazrat Shahjalal International Airport)</option>
                            <option value="Kolkata (Netaji Subhash Chandra Bose International Airport)">Kolkata (Netaji Subhash Chandra Bose International Airport)</option>
                            <option value="Chennai (Chennai International Airport)">Chennai (Chennai International Airport)</option>
                            <option value="Delhi (Indira Gandhi International Airport)">Delhi (Indira Gandhi International Airport)</option>
                            <option value="Mumbai (Chattrapati Shivaji International Airport)">Mumbai (Chattrapati Shivaji International Airport)</option>
                        </select>
    
                    </div>
                </div>
                <div class="col-md-6 col-12 mb-4">
                    <div class="form-control d-flex flex-column fs-3">
                        <p class="h-blue fw-bold">FLYING TO</p>
    
                        <select class="border-0 outline-none" name="flying_to" required>
                            <option value="" hidden selected>City or Airport</option>
                            <option value="Dhaka (Hazrat Shahjalal International Airport)">Dhaka (Hazrat Shahjalal International Airport)</option>
                            <option value="Kolkata (Netaji Subhash Chandra Bose International Airport)">Kolkata (Netaji Subhash Chandra Bose International Airport)</option>
                            <option value="Chennai (Chennai International Airport)">Chennai (Chennai International Airport)</option>
                            <option value="Delhi (Indira Gandhi International Airport)">Delhi (Indira Gandhi International Airport)</option>
                            <option value="Mumbai (Chattrapati Shivaji International Airport)">Mumbai (Chattrapati Shivaji International Airport)</option>
                        </select>
    
                    </div>
                </div>
            </div>
    
            <div class="row">
                <div class="col-md-6 col-12 mb-4">
                    <div class="form-control d-flex flex-column">
                        <p class="h-blue fw-bold">DEPARTING</p> <input class="inputbox fs-4" type="date" name="departing" required>
                    </div>
                </div>
                <div class="col-md-6 col-12 mb-4">
                    <div class="form-control d-flex flex-column">
                        <p class="h-blue fw-bold">RETURNING</p> <input class="inputbox fs-4" type="date" name="returning">
                    </div>
                </div>
            </div>
    
            <div class="row">
    
                <div class="col-md-4 mb-4">
                    <div class="form-control d-flex flex-column fs-3 fw-bold">
                        <p class="h-blue fw-bold">ADULTS(18+)</p> <select class="border-0 outline-none" name="adults" required>
                            <option value="" hidden selected>Open this select menu</option>
                            <option value="1">One</option>
                            <option value="2">Two</option>
                            <option value="3">Three</option>
                            <option value="4">Four</option>
                            <option value="5">Five</option>
                        </select>
                    </div>
                </div>
    
                <div class="col-md-4 mb-4">
                    <div class="form-control d-flex flex-column fs-3 fw-bold">
                        <p class="h-blue fw-bold">CHILDREN(0-17)</p> <select class="border-0 outline-none" name="children" required>
                            <option value="" hidden selected>Open this select menu</option>
                            <option value="1">One</option>
                            <option value="2">Two</option>
                            <option value="3">Three</option>
                            <option value="4">Four</option>
                            <option value="5">Five</option>
                        </select>
                    </div>
                </div>
    
                <div class="col-md-4 mb-4">
                    <div class="form-control d-flex flex-column fs-3 fw-bold">
                        <p class="h-blue fw-bold">TRAVEL CLASS</p> <select class="border-0 outline-none" name="travel_class" required>
                            <option value="" hidden selected>Class Select</option>
                            <option value="Economy">Economy</option>
                            <option value="Premium">Premium</option>
                            <option value="Business">Business</option>
                        </select>
                    </div>
                </div>
    
            </div>
    
            <div class="d-grid gap-2 col-6 mx-auto mt-4">
                <button class="btn btn-warning" type="submit" style="height: 50px;"><strong>FLIGHTS BOOKING</strong></button>
            </div>

        </form>
    </div>










    <div class="content">


        <!-- <h3>adventure is worthwhile</h3>
        <p>dicover new places with us, adventure awaits</p> -->
        <!-- <a href="#" class="btn">discover more</a> -->
    </div>

    <div class="video-container">
        <video src="{% static 'images/vid-1.mp4' %}" id="video-slider" loop autoplay muted></video>
    </div>


    {% endif %}


</section>
<!-- home section ends -->

{% endblock %}